"use client";

import { useCallback, useEffect, useState } from "react";
import type { SettingsDto } from "@/lib/domain/settings";
import { Button } from "@/components/ui/Button";

const weekdays = ["일", "월", "화", "수", "목", "금", "토"];

async function jsonApi<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, { ...init, headers: { ...(init?.body ? { "Content-Type": "application/json" } : {}), ...init?.headers }, cache: "no-store" });
  const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "요청을 처리하지 못했습니다."); return body.data;
}

export function SettingsPanel() {
  const [settings, setSettings] = useState<SettingsDto | null>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const load = useCallback(() => jsonApi<SettingsDto>("/api/teacher/settings").then(setSettings).catch((value) => setError(value.message)), []);
  useEffect(() => { void load(); }, [load]);
  return <div className="stack"><div><h1>설정</h1><p className="supporting">활동을 시작하기 전에 연결 상태와 운영 설정을 확인하세요.</p></div><div className={`status-line ${error ? "status-line--error" : "status-line--success"}`} role="status" aria-live="polite">{error || notice}</div>{settings && <><section className="readiness" aria-labelledby="ready-title"><div className="row row--between"><h2 id="ready-title" style={{ fontSize: 19, marginBottom: 4 }}>준비 상태</h2><Button type="button" tone={settings.paused ? "primary" : "danger"} onClick={async()=>{try{await jsonApi("/api/teacher/settings",{method:"PATCH",body:JSON.stringify({settingsVersion:settings.settingsVersion,paused:!settings.paused})});setNotice(settings.paused?"운영 입력을 활성화했습니다.":"운영 입력을 중지했습니다.");setError("");load();}catch(value){setError(value instanceof Error?value.message:"상태를 변경하지 못했습니다.");}}}>{settings.paused?"운영 활성화":"긴급 중지"}</Button></div>{settings.readiness.map((item) => <div className="readiness-row" key={item.key}><span>{item.label}<span className="small muted" style={{ display: "block" }}>{item.detail}</span></span><span className={`badge ${item.ready ? "badge--success" : "badge--danger"}`}>{item.ready ? "준비됨" : "확인 필요"}</span></div>)}</section><div className="settings-list"><ScheduleSection settings={settings} changed={load} setError={setError} setNotice={setNotice} /><PinSection changed={load} setError={setError} setNotice={setNotice} /><TeacherSourceSection settings={settings} changed={load} setError={setError} setNotice={setNotice}/><details><summary>학교 PC 연결</summary><div className="settings-content stack stack--tight"><div className="readiness-row"><span>중계 상태</span><strong>{settings.bridge.online ? "온라인" : "연결 끊김"}</strong></div><div className="readiness-row"><span>원본 입력</span><strong>{settings.bridge.penaltyReady ? "가능" : "불가"}</strong></div><div className="readiness-row"><span>자동 취소</span><strong>{settings.bridge.cancellationReady ? "가능" : "수동 확인 필요"}</strong></div></div></details><InvitationSection setError={setError} setNotice={setNotice} /><AccessibilitySection setNotice={setNotice} /></div></>}</div>;
}

function ScheduleSection({ settings, changed, setError, setNotice }: { settings: SettingsDto; changed: () => void; setError: (v: string) => void; setNotice: (v: string) => void }) {
  const [openEditor, setOpenEditor] = useState(false); const [name, setName] = useState(""); const [start, setStart] = useState("07:40"); const [end, setEnd] = useState("08:30"); const [days, setDays] = useState([1,2,3,4,5]); const[allowed,setAllowed]=useState<string[]>([]);
  async function save() { try { await jsonApi("/api/teacher/settings", { method: "POST", body: JSON.stringify({ name, weekdays: days, startLocal: start, endLocal: end, enabled: true, allowedItemKeys: allowed }) }); setNotice("활동시간을 저장했습니다."); setError(""); setOpenEditor(false); changed(); } catch (value) { setError(value instanceof Error ? value.message : "저장하지 못했습니다."); } }
  return <details open><summary>활동시간</summary><div className="settings-content stack"><div className="history-list">{settings.schedules.map((schedule) => <div className="history-row" key={schedule.id}><div><strong>{schedule.name}</strong><span className="small muted" style={{ display: "block" }}>{schedule.weekdays.map((day) => weekdays[day]).join("·")} · {schedule.startLocal}–{schedule.endLocal}</span><span className="small muted">항목 {schedule.allowedItemKeys.length}개</span></div><span className={`badge ${schedule.enabled ? "badge--success" : ""}`}>{schedule.enabled ? "사용" : "중지"}</span></div>)}</div>{openEditor ? <div className="stack"><input className="input" aria-label="활동 이름" placeholder="활동 이름" value={name} onChange={(event) => setName(event.target.value)} /><div className="row"><div className="field grow"><label htmlFor="start">시작</label><input id="start" className="input" type="time" value={start} onChange={(event) => setStart(event.target.value)} /></div><div className="field grow"><label htmlFor="end">종료</label><input id="end" className="input" type="time" value={end} onChange={(event) => setEnd(event.target.value)} /></div></div><div className="row row--wrap" aria-label="활동 요일">{weekdays.map((day, index) => <button className="item-button" style={{ minWidth: 48 }} type="button" key={day} aria-pressed={days.includes(index)} onClick={() => setDays(days.includes(index) ? days.filter((value) => value !== index) : [...days, index])}>{day}</button>)}</div><div><span className="field-label">허용 벌점 항목</span><div className="item-grid" style={{marginTop:8}}>{settings.penaltyItems.map((item)=><button className="item-button" type="button" key={item.key} aria-pressed={allowed.includes(item.key)} onClick={()=>setAllowed(allowed.includes(item.key)?allowed.filter((key)=>key!==item.key):[...allowed,item.key])}>{item.label} · {Math.abs(item.signedPoints)}점</button>)}</div></div><div className="row"><Button tone="quiet" onClick={() => setOpenEditor(false)}>취소</Button><Button tone="primary" className="grow" disabled={!name.trim() || !days.length || !allowed.length} onClick={() => void save()}>활동 저장</Button></div></div> : <Button type="button" onClick={() => {setAllowed(settings.penaltyItems.filter(item=>item.enabled).slice(0,4).map(item=>item.key));setOpenEditor(true);}}>활동 추가</Button>}</div></details>;
}

function TeacherSourceSection({settings,changed,setError,setNotice}:{settings:SettingsDto;changed:()=>void;setError:(v:string)=>void;setNotice:(v:string)=>void}){const[selected,setSelected]=useState(settings.teacherSourceId??"");async function save(){try{await jsonApi("/api/teacher/settings",{method:"PATCH",body:JSON.stringify({settingsVersion:settings.settingsVersion,teacherSourceId:selected})});setNotice("담당교사를 연결했습니다.");setError("");changed();}catch(value){setError(value instanceof Error?value.message:"담당교사를 연결하지 못했습니다.");}}return <details><summary>담당교사</summary><div className="settings-content stack"><p>원본 유니쿨의 검증된 교사 식별값을 사용합니다. 이메일이나 이름으로 자동 연결하지 않습니다.</p><select className="input" aria-label="원본 담당교사" value={selected} onChange={(event)=>setSelected(event.target.value)}><option value="">담당교사 선택</option>{settings.sourceTeachers.filter(item=>item.active).map(item=><option key={item.id} value={item.id}>{item.name} · {item.id}</option>)}</select><Button tone="primary" disabled={!selected} onClick={()=>void save()}>담당교사 연결</Button></div></details>}

function PinSection({ changed, setError, setNotice }: { changed: () => void; setError: (v: string) => void; setNotice: (v: string) => void }) {
  const [pin, setPin] = useState(""); const [confirmation, setConfirmation] = useState("");
  async function save() { try { await jsonApi("/api/teacher/settings/pin", { method: "POST", body: JSON.stringify({ pin, confirmation }) }); setPin(""); setConfirmation(""); setError(""); setNotice("PIN을 변경했습니다. 기존 학생회 세션은 종료됩니다."); changed(); } catch (value) { setError(value instanceof Error ? value.message : "PIN을 변경하지 못했습니다."); } }
  return <details><summary>활동 PIN</summary><div className="settings-content stack"><p>변경하면 현재 열린 모든 학생회 활동이 종료됩니다.</p><input className="input input--pin" aria-label="새 PIN" type="password" inputMode="numeric" autoComplete="new-password" maxLength={6} value={pin} onChange={(event) => setPin(event.target.value.replace(/\D/g, "").slice(0,6))} /><input className="input input--pin" aria-label="새 PIN 확인" type="password" inputMode="numeric" autoComplete="new-password" maxLength={6} value={confirmation} onChange={(event) => setConfirmation(event.target.value.replace(/\D/g, "").slice(0,6))} /><Button tone="primary" disabled={pin.length !== 6 || confirmation.length !== 6} onClick={() => void save()}>PIN 변경</Button></div></details>;
}

function InvitationSection({ setError, setNotice }: { setError: (v: string) => void; setNotice: (v: string) => void }) {
  const [email, setEmail] = useState(""); const [role, setRole] = useState<"teacher" | "admin">("teacher"); const [inviteLink,setInviteLink]=useState("");
  async function invite() { try { const invitation=await jsonApi<{inviteUrl?:string}>("/api/teacher/invitations", { method: "POST", body: JSON.stringify({ email, role }) }); setInviteLink(invitation.inviteUrl??""); setEmail(""); setError(""); setNotice("교사 초대 링크를 만들었습니다. 안전한 교내 메신저로 전달하세요."); } catch (value) { setError(value instanceof Error ? value.message : "초대하지 못했습니다."); } }
  return <details><summary>교사 관리</summary><div className="settings-content stack"><p>공개 회원가입과 외부 메일 발송은 없습니다. 생성한 일회용 링크를 교내에서 직접 전달합니다. 같은 이메일을 다시 초대하면 비밀번호를 재설정할 수 있습니다.</p><input className="input" type="email" aria-label="초대할 교사 이메일" placeholder="teacher@school.kr" value={email} onChange={(event) => setEmail(event.target.value)} /><select className="input" aria-label="초대 역할" value={role} onChange={(event) => setRole(event.target.value as "teacher" | "admin")}><option value="teacher">교사</option><option value="admin">관리자</option></select><Button tone="primary" disabled={!email.includes("@")} onClick={() => void invite()}>일회용 초대 링크 만들기</Button>{inviteLink&&<div className="stack stack--tight"><label htmlFor="invite-link">24시간 유효한 초대 링크</label><input id="invite-link" className="input" readOnly value={inviteLink}/><Button type="button" onClick={async()=>{await navigator.clipboard.writeText(inviteLink);setNotice("초대 링크를 복사했습니다.");}}>링크 복사</Button></div>}</div></details>;
}

function AccessibilitySection({ setNotice }: { setNotice: (v: string) => void }) {
  const [reduced, setReduced] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { const value = localStorage.getItem("hguni-reduce-transparency") === "true"; setReduced(value); document.documentElement.classList.toggle("reduce-transparency", value); }, 0); return () => window.clearTimeout(timer); }, []);
  function toggle() { const value = !reduced; setReduced(value); localStorage.setItem("hguni-reduce-transparency", String(value)); document.documentElement.classList.toggle("reduce-transparency", value); setNotice(value ? "이 장치에서 투명도를 줄였습니다." : "이 장치에서 광학 효과를 사용합니다."); }
  return <details><summary>화면 접근성</summary><div className="settings-content"><div className="readiness-row"><span><strong>투명도 줄이기</strong><span className="small muted" style={{ display: "block" }}>이 브라우저에만 저장됩니다.</span></span><Button type="button" aria-pressed={reduced} onClick={toggle}>{reduced ? "사용 중" : "사용 안 함"}</Button></div></div></details>;
}
